---
- name: Setup webserver
  hosts: webservers  
  remote_user: admin


  tasks:
  
  - name: Install nginx & php8.1
    script: scripts/nginx.sh

  - name: Replace php default site file
    copy:
        src: mytemplates/default
        dest: /etc/nginx/sites-available/default
    become: yes
  
  - name: Copy index.php
    copy:
        src: mytemplates/index.php
        dest: /var/www/html/index.php
    become: yes

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    become: yes
  
      


